package locallink

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/sneat-dev/wb/internal/streams"
)

// The two files a Go link creates are named by the streams package, so the
// verb that writes them and the verbs that refuse on them cannot disagree.
const (
	goWorkFile = streams.GoWorkFile
	goWorkSum  = streams.GoWorkSum
)

// linkGo writes the consumer's workspace.
//
// The `use` entries name **every** Go module in the consumer worktree —
// `backend/`, the module root where there is no `backend/`, and any nested
// tooling module — **plus** the library worktree's modules. A workspace holding
// only the library would leave the consumer's own module outside the workspace
// it now sits under, and `go build ./...` in `backend/` would not resolve at
// all.
//
// `go.mod` is never touched: no `replace` directive is added, and CI is
// unaffected for a structural reason rather than a conventional one — the file
// does not exist in the repository, so a CI checkout has no `go.work` to
// honour. `GOWORK=off` is the explicit guarantee where a toolchain might
// discover one anyway.
func (engine *Engine) linkGo(
	ctx context.Context,
	library, consumer string,
	declarations []streams.Declaration,
	libraryRepository, hash string,
) ([]streams.Link, error) {
	consumerModules, err := streams.GoModules(consumer)
	if err != nil {
		return nil, err
	}
	if len(consumerModules) == 0 {
		return nil, fmt.Errorf("%s declares a Go dependency on the library but contains no go.mod", consumer)
	}
	libraryModules, err := streams.GoModules(library)
	if err != nil {
		return nil, err
	}
	if len(libraryModules) == 0 {
		return nil, fmt.Errorf("%s contains no go.mod to place in the workspace", library)
	}
	contents, err := renderGoWork(consumer, consumerModules, library, libraryModules)
	if err != nil {
		return nil, err
	}
	// The exclude is written *before* the file, so the workspace never exists
	// for even one moment as an includable untracked path.
	for _, pattern := range []string{"/" + goWorkFile, "/" + goWorkSum} {
		if err := engine.Git.ExcludePath(ctx, consumer, pattern); err != nil {
			return nil, err
		}
	}
	if err := os.WriteFile(filepath.Join(consumer, goWorkFile), []byte(contents), 0o644); err != nil {
		return nil, fmt.Errorf("write %s: %w", goWorkFile, err)
	}
	now := engine.now()
	links := make([]streams.Link, 0, len(declarations))
	for _, declaration := range declarations {
		links = append(links, streams.Link{
			Library:           library,
			LibraryRepository: libraryRepository,
			Mechanism:         streams.MechanismGoWork,
			Identity:          declaration.Identity.Name,
			PreviousVersion:   declaration.Version,
			ContentHash:       hash,
			Artifacts:         []string{goWorkFile, goWorkSum},
			CreatedAt:         now,
		})
	}
	return links, nil
}

// renderGoWork produces the workspace file. Consumer modules are relative so
// the file reads the same wherever the worktree sits; the library is absolute
// because it lives outside the consumer's tree.
func renderGoWork(consumer string, consumerModules []streams.GoModule, library string, libraryModules []streams.GoModule) (string, error) {
	version := goDirective(consumer, consumerModules)
	uses := make([]string, 0, len(consumerModules)+len(libraryModules))
	for _, module := range consumerModules {
		uses = append(uses, "./"+strings.TrimPrefix(module.Directory, "./"))
	}
	for _, module := range libraryModules {
		path := library
		if module.Directory != "." {
			path = filepath.Join(library, filepath.FromSlash(module.Directory))
		}
		uses = append(uses, filepath.ToSlash(path))
	}
	sort.Strings(uses)
	var builder strings.Builder
	builder.WriteString("// Generated by `wb deps propagate local`. Untracked and Git-excluded.\n")
	builder.WriteString("// It makes this consumer build against the library's WORKING TREE, not a\n")
	builder.WriteString("// published version. Run with GOWORK=off to resolve the published version\n")
	builder.WriteString("// instead. Remove it with `wb deps propagate local --undo`; never commit it,\n")
	builder.WriteString("// and never run `go mod tidy` or `go get` while it exists.\n")
	if version != "" {
		builder.WriteString("\ngo " + version + "\n")
	}
	builder.WriteString("\nuse (\n")
	for _, use := range uses {
		builder.WriteString("\t" + use + "\n")
	}
	builder.WriteString(")\n")
	return builder.String(), nil
}

var goVersionDirective = regexp.MustCompile(`(?m)^\s*go\s+([0-9]+(?:\.[0-9]+){0,2})`)

// goDirective reads the consumer's own `go` directive so the workspace never
// declares a language version the consumer's modules do not have.
func goDirective(root string, modules []streams.GoModule) string {
	best := ""
	for _, module := range modules {
		contents, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(module.Manifest)))
		if err != nil {
			continue
		}
		match := goVersionDirective.FindSubmatch(contents)
		if match == nil {
			continue
		}
		candidate := string(match[1])
		if best == "" || compareGoVersions(candidate, best) > 0 {
			best = candidate
		}
	}
	return best
}

func compareGoVersions(left, right string) int {
	leftParts := strings.Split(left, ".")
	rightParts := strings.Split(right, ".")
	for index := 0; index < len(leftParts) || index < len(rightParts); index++ {
		leftValue, rightValue := 0, 0
		if index < len(leftParts) {
			_, _ = fmt.Sscanf(leftParts[index], "%d", &leftValue)
		}
		if index < len(rightParts) {
			_, _ = fmt.Sscanf(rightParts[index], "%d", &rightValue)
		}
		if leftValue != rightValue {
			if leftValue > rightValue {
				return 1
			}
			return -1
		}
	}
	return 0
}

// removeGoWork deletes the workspace files. It never removes the exclude
// entries: an exclude for a file that does not exist is inert, and removing it
// would rewrite a file the operator may have edited.
func removeGoWork(consumer string) error {
	for _, name := range []string{goWorkFile, goWorkSum} {
		if err := os.Remove(filepath.Join(consumer, name)); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove %s: %w", name, err)
		}
	}
	return nil
}

// GoWorkUseEntries reads the `use` entries of a worktree's go.work.
//
// It delegates to the streams package, which is where `wb worktree end` reads
// the same signal. Two copies of this parser would drift, and the file-based
// half of the merge refusal is exactly the check that must not disagree with
// itself between two verbs.
func GoWorkUseEntries(consumer string) ([]string, error) {
	return streams.GoWorkUseEntries(consumer)
}
