package locallink

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sneat-dev/wb/internal/streams"
)

// lgCovGoWorkLink is one recorded go.work link against library.
func lgCovGoWorkLink(library string) streams.Link {
	return streams.Link{
		Library: library, Mechanism: streams.MechanismGoWork, State: streams.LinkStateApplied,
		Identity: "github.com/acme/library/backend", PreviousVersion: "v0.4.0",
		Artifacts: []string{streams.GoWorkFile, streams.GoWorkSum},
	}
}

func lgCovPnpmLink(library, identity, workspace string) streams.Link {
	return streams.Link{
		Library: library, Mechanism: streams.MechanismPnpmLink, State: streams.LinkStateApplied,
		Identity: identity, PreviousVersion: "1.0.0", Workspace: workspace,
	}
}

// lgCovWriteGoWork makes a consumer genuinely linked, so undo has something
// real to remove.
func lgCovWriteGoWork(t *testing.T, consumer, library string) {
	t.Helper()
	body := "// Generated by `wb deps propagate local`.\n\ngo 1.27\n\nuse (\n\t" + library + "\n)\n"
	lgCovWriteFile(t, filepath.Join(consumer, streams.GoWorkFile), body)
}

func TestLgCovUndoRequiresReadableState(t *testing.T) {
	ctx := context.Background()

	t.Run("no store", func(t *testing.T) {
		engine := &Engine{}
		_, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{t.TempDir()}})
		if err == nil || !strings.Contains(err.Error(), "no stream state is available") {
			t.Fatalf("error = %v, want the no-store refusal", err)
		}
	})

	t.Run("unreadable store", func(t *testing.T) {
		notADirectory := filepath.Join(t.TempDir(), "store")
		lgCovWriteFile(t, notADirectory, "not a directory\n")
		engine := &Engine{Store: streams.OpenAt(notADirectory)}
		_, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{t.TempDir()}})
		if err == nil || !strings.Contains(err.Error(), "read stream store") {
			t.Fatalf("error = %v, want the unreadable store reported", err)
		}
	})

	t.Run("an unreadable stream refuses the undo", func(t *testing.T) {
		store := streams.OpenAt(filepath.Join(t.TempDir(), "streams"))
		lgCovWriteFile(t, filepath.Join(store.Root, "broken", "stream.json"), "{not json")
		engine := &Engine{Store: store}
		_, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{t.TempDir()}})
		if err == nil || !strings.Contains(err.Error(), "stream state is unreadable for broken") {
			t.Fatalf("error = %v, want the unreadable-stream refusal", err)
		}
	})
}

// A named stream filter and a consumer filter each skip records rather than
// acting on them, and an unmatched consumer with no go.work is reported as
// skipped rather than failed.
func TestLgCovUndoFiltersAndSkippedOutcome(t *testing.T) {
	ctx := context.Background()
	base := t.TempDir()
	library := filepath.Join(base, "library")
	consumerA := filepath.Join(base, "consumer-a")
	consumerB := filepath.Join(base, "consumer-b")
	lgCovWriteGoWork(t, consumerA, library)
	lgCovWriteGoWork(t, consumerB, library)

	store := streams.OpenAt(filepath.Join(base, "streams"))
	if _, err := store.Create(streams.Stream{
		Name: "fixture",
		Members: []streams.Member{
			{Repository: "acme/app", Role: streams.RoleConsumer, Worktree: consumerA, Links: []streams.Link{lgCovGoWorkLink(library)}},
		},
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := store.Create(streams.Stream{
		Name: "other",
		Members: []streams.Member{
			{Repository: "acme/app", Role: streams.RoleConsumer, Worktree: consumerB, Links: []streams.Link{lgCovGoWorkLink(library)}},
		},
	}); err != nil {
		t.Fatal(err)
	}

	t.Run("a stream name filter skips other streams", func(t *testing.T) {
		engine := &Engine{Store: store}
		result, err := engine.Run(ctx, Options{Undo: true, Stream: "other"})
		if err != nil || result.Failed() {
			t.Fatalf("undo = %#v, err = %v", result.Consumers, err)
		}
		if result.Stream != "other" || len(result.Consumers) != 1 || result.Consumers[0].Consumer != consumerB {
			t.Fatalf("undo = %#v (stream %q), want only the named stream's consumer", result.Consumers, result.Stream)
		}
		if !fileExists(filepath.Join(consumerA, streams.GoWorkFile)) {
			t.Fatal("undo under a stream filter touched a worktree in another stream")
		}
	})

	t.Run("a consumer filter skips every non-matching record", func(t *testing.T) {
		// Re-create the state the previous subtest removed.
		lgCovWriteGoWork(t, consumerB, library)
		engine := &Engine{Store: store}
		stranger := t.TempDir()
		result, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{stranger}})
		if err != nil || result.Failed() {
			t.Fatalf("undo = %#v, err = %v", result.Consumers, err)
		}
		if len(result.Consumers) != 1 || !result.Consumers[0].Skipped {
			t.Fatalf("undo = %#v, want one skipped unrecorded consumer", result.Consumers)
		}
		if !strings.Contains(result.Consumers[0].Reason, "no recorded link and no go.work") {
			t.Fatalf("reason = %q, want the nothing-to-undo explanation", result.Consumers[0].Reason)
		}
		if !fileExists(filepath.Join(consumerB, streams.GoWorkFile)) {
			t.Fatal("undo with a consumer filter removed a link it was not asked about")
		}
	})

	t.Run("no records and no consumers reports a skipped result", func(t *testing.T) {
		empty := streams.OpenAt(filepath.Join(t.TempDir(), "streams"))
		if _, err := empty.Create(streams.Stream{Name: "fixture"}); err != nil {
			t.Fatal(err)
		}
		engine := &Engine{Store: empty}
		result, err := engine.Run(ctx, Options{Undo: true})
		if err != nil || result.Failed() {
			t.Fatalf("undo = %#v, err = %v", result.Consumers, err)
		}
		if len(result.Consumers) != 1 || !result.Consumers[0].Skipped || result.Consumers[0].Consumer != "" {
			t.Fatalf("undo = %#v, want one skipped empty-consumer result", result.Consumers)
		}
	})
}

// LinkedConsumers carry the same link shape as Members and must be undone the
// same way, with non-matching and link-free bindings left alone.
func TestLgCovUndoLinkedConsumersFiltering(t *testing.T) {
	ctx := context.Background()
	base := t.TempDir()
	library := filepath.Join(base, "library")
	linked := filepath.Join(base, "linked")
	linkFree := filepath.Join(base, "link-free")
	other := filepath.Join(base, "other")
	for _, consumer := range []string{linked, linkFree, other} {
		lgCovWriteGoWork(t, consumer, library)
	}
	store := streams.OpenAt(filepath.Join(base, "streams"))
	if _, err := store.Create(streams.Stream{
		Name: "fixture",
		LinkedConsumers: []streams.LinkedConsumerBinding{
			{Repository: "acme/linked", Worktree: linked, Links: []streams.Link{lgCovGoWorkLink(library)}},
			{Repository: "acme/link-free", Worktree: linkFree},
			{Repository: "acme/other", Worktree: other, Links: []streams.Link{lgCovGoWorkLink(library)}},
		},
	}); err != nil {
		t.Fatal(err)
	}

	engine := &Engine{Store: store}
	result, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{linked}})
	if err != nil || result.Failed() {
		t.Fatalf("undo = %#v, err = %v", result.Consumers, err)
	}
	if len(result.Consumers) != 1 || result.Consumers[0].Consumer != linked {
		t.Fatalf("undo = %#v, want only the filtered-in LinkedConsumer", result.Consumers)
	}
	if fileExists(filepath.Join(linked, streams.GoWorkFile)) {
		t.Error("the matching LinkedConsumer's go.work survived undo")
	}
	for _, untouched := range []string{linkFree, other} {
		if !fileExists(filepath.Join(untouched, streams.GoWorkFile)) {
			t.Fatalf("undo removed a go.work for a binding it was not asked about: %s", untouched)
		}
	}

	stream, err := store.Load("fixture")
	if err != nil {
		t.Fatal(err)
	}
	binding, _ := stream.LinkedConsumer("acme/linked")
	if len(binding.Links) != 0 {
		t.Fatalf("the undone binding kept its record: %#v", binding.Links)
	}
	keptBinding, _ := stream.LinkedConsumer("acme/other")
	if len(keptBinding.Links) != 1 {
		t.Fatalf("a skipped binding lost its record: %#v", keptBinding.Links)
	}
}

// A record that cannot be cleared is reported; the record stays so the merge
// guard keeps refusing.
func TestLgCovUndoReportsUnclearableRecords(t *testing.T) {
	ctx := context.Background()

	t.Run("an unlocked store refuses the clear", func(t *testing.T) {
		base := t.TempDir()
		library := filepath.Join(base, "library")
		consumer := filepath.Join(base, "consumer")
		lgCovWriteGoWork(t, consumer, library)
		store := streams.OpenAt(filepath.Join(base, "streams"))
		if _, err := store.Create(streams.Stream{
			Name:    "fixture",
			Members: []streams.Member{{Repository: "acme/app", Role: streams.RoleConsumer, Worktree: consumer, Links: []streams.Link{lgCovGoWorkLink(library)}}},
		}); err != nil {
			t.Fatal(err)
		}
		// A directory where the lock file belongs makes Update fail.
		if err := os.MkdirAll(filepath.Join(store.Dir("fixture"), "stream.lock"), 0o755); err != nil {
			t.Fatal(err)
		}
		engine := &Engine{Store: store}
		result, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{consumer}})
		if err == nil || !strings.Contains(err.Error(), "clear link records in stream fixture") {
			t.Fatalf("err = %v, want the failed clear reported (result %#v)", err, result.Consumers)
		}
	})

	t.Run("an unrecorded go.work that cannot be read is reported", func(t *testing.T) {
		store := streams.OpenAt(filepath.Join(t.TempDir(), "streams"))
		consumer := t.TempDir()
		if err := os.Mkdir(filepath.Join(consumer, streams.GoWorkFile), 0o755); err != nil {
			t.Fatal(err)
		}
		engine := &Engine{Store: store}
		result, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{consumer}})
		if err != nil {
			t.Fatal(err)
		}
		if len(result.Consumers) != 1 || len(result.Consumers[0].Errors) == 0 {
			t.Fatalf("consumers = %#v, want the unreadable go.work reported", result.Consumers)
		}
	})

	t.Run("an unrecorded go.work that cannot be removed is reported", func(t *testing.T) {
		store := streams.OpenAt(filepath.Join(t.TempDir(), "streams"))
		consumer := t.TempDir()
		lgCovWriteGoWork(t, consumer, filepath.Join(t.TempDir(), "library"))
		sumPath := filepath.Join(consumer, streams.GoWorkSum)
		if err := os.MkdirAll(sumPath, 0o755); err != nil {
			t.Fatal(err)
		}
		lgCovWriteFile(t, filepath.Join(sumPath, "keep.txt"), "keep\n")
		engine := &Engine{Store: store}
		result, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{consumer}})
		if err != nil {
			t.Fatal(err)
		}
		if len(result.Consumers) != 1 || len(result.Consumers[0].Errors) == 0 {
			t.Fatalf("consumers = %#v, want the failed removal reported", result.Consumers)
		}
		if !fileExists(sumPath) {
			t.Error("a failed removal consumed what it could not delete")
		}
	})
}

// undoLinks' per-mechanism branches: repeated go.work records, an unreadable
// workspace, a failed removal, unknown states, a missing Node toolchain and an
// unknown mechanism.
func TestLgCovUndoLinksMechanismBranches(t *testing.T) {
	ctx := context.Background()

	t.Run("repeated go.work records are undone once", func(t *testing.T) {
		base := t.TempDir()
		library := filepath.Join(base, "library")
		consumer := filepath.Join(base, "consumer")
		lgCovWriteGoWork(t, consumer, library)
		store := streams.OpenAt(filepath.Join(base, "streams"))
		if _, err := store.Create(streams.Stream{
			Name: "fixture",
			Members: []streams.Member{{Repository: "acme/app", Role: streams.RoleConsumer, Worktree: consumer,
				Links: []streams.Link{lgCovGoWorkLink(library), lgCovGoWorkLink(library)}}},
		}); err != nil {
			t.Fatal(err)
		}
		engine := &Engine{Store: store}
		result, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{consumer}})
		if err != nil || result.Failed() {
			t.Fatalf("undo = %#v, err = %v", result.Consumers, err)
		}
		if fileExists(filepath.Join(consumer, streams.GoWorkFile)) {
			t.Error("go.work survived undo of duplicated records")
		}
	})

	t.Run("an unreadable workspace is reported and kept", func(t *testing.T) {
		base := t.TempDir()
		library := filepath.Join(base, "library")
		consumer := filepath.Join(base, "consumer")
		if err := os.MkdirAll(filepath.Join(consumer, streams.GoWorkFile), 0o755); err != nil {
			t.Fatal(err)
		}
		store := streams.OpenAt(filepath.Join(base, "streams"))
		if _, err := store.Create(streams.Stream{
			Name:    "fixture",
			Members: []streams.Member{{Repository: "acme/app", Role: streams.RoleConsumer, Worktree: consumer, Links: []streams.Link{lgCovGoWorkLink(library)}}},
		}); err != nil {
			t.Fatal(err)
		}
		engine := &Engine{Store: store}
		result, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{consumer}})
		if err != nil {
			t.Fatal(err)
		}
		if len(result.Consumers[0].Errors) == 0 {
			t.Fatalf("consumers = %#v, want the unreadable workspace reported", result.Consumers)
		}
		stream, err := store.Load("fixture")
		if err != nil {
			t.Fatal(err)
		}
		if len(stream.Members[0].Links) != 1 {
			t.Fatalf("links = %#v, want the failed removal to keep its record", stream.Members[0].Links)
		}
	})

	t.Run("a failed workspace removal is reported and kept", func(t *testing.T) {
		base := t.TempDir()
		library := filepath.Join(base, "library")
		consumer := filepath.Join(base, "consumer")
		lgCovWriteGoWork(t, consumer, library)
		sumPath := filepath.Join(consumer, streams.GoWorkSum)
		if err := os.MkdirAll(sumPath, 0o755); err != nil {
			t.Fatal(err)
		}
		lgCovWriteFile(t, filepath.Join(sumPath, "keep.txt"), "keep\n")
		store := streams.OpenAt(filepath.Join(base, "streams"))
		if _, err := store.Create(streams.Stream{
			Name:    "fixture",
			Members: []streams.Member{{Repository: "acme/app", Role: streams.RoleConsumer, Worktree: consumer, Links: []streams.Link{lgCovGoWorkLink(library)}}},
		}); err != nil {
			t.Fatal(err)
		}
		engine := &Engine{Store: store}
		result, err := engine.Run(ctx, Options{Undo: true, Consumers: []string{consumer}})
		if err != nil {
			t.Fatal(err)
		}
		if len(result.Consumers[0].Errors) == 0 {
			t.Fatalf("consumers = %#v, want the failed removal reported", result.Consumers)
		}
		stream, err := store.Load("fixture")
		if err != nil {
			t.Fatal(err)
		}
		if len(stream.Members[0].Links) != 1 {
			t.Fatalf("links = %#v, want the failed removal to keep its record", stream.Members[0].Links)
		}
	})

	t.Run("unknown states, missing node and unknown mechanisms are refused", func(t *testing.T) {
		base := t.TempDir()
		consumer := filepath.Join(base, "consumer")
		if err := os.MkdirAll(consumer, 0o755); err != nil {
			t.Fatal(err)
		}
		links := []streams.Link{
			{Mechanism: streams.MechanismPnpmLink, State: streams.LinkState("bogus"), Identity: "@acme/core"},
			{Mechanism: streams.MechanismPnpmLink, State: streams.LinkStateApplied, Identity: "@acme/auth"},
			{Mechanism: streams.Mechanism("bogus"), Identity: "@acme/weird"},
		}
		engine := &Engine{Store: streams.OpenAt(filepath.Join(base, "streams"))}
		outcome, remaining := engine.undoLinks(ctx, consumer, links)
		if len(outcome.Errors) != 3 {
			t.Fatalf("errors = %#v, want one per refused link", outcome.Errors)
		}
		for _, wanted := range []string{"unknown link state", "no Node toolchain", "unknown link mechanism"} {
			if !containsSubstring(outcome.Errors, wanted) {
				t.Fatalf("errors = %#v, want %q", outcome.Errors, wanted)
			}
		}
		if len(remaining) != 3 {
			t.Fatalf("remaining = %#v, want every refused link kept", remaining)
		}
	})
}

func TestLgCovFirstOrEmpty(t *testing.T) {
	if got := firstOrEmpty(nil); got != "" {
		t.Fatalf("firstOrEmpty(nil) = %q, want empty", got)
	}
	if got := firstOrEmpty([]string{"first", "second"}); got != "first" {
		t.Fatalf("firstOrEmpty = %q, want the first value", got)
	}
}
