package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/sneat-dev/wb/internal/daemonruntime"
	"github.com/sneat-dev/wb/internal/peers"

	"github.com/sneat-dev/wb/internal/daemon"
)

// peersRPCPrefix is the path family peer-connectivity#req:admin-requires-
// owner-credential's owner-token RPC serves invite, rotate (folded into
// invite's --rotate), block, unblock and disconnect on. It shares the same
// unix-socket server and authenticatedDaemonHandler wrapper as the
// connect-go DaemonService, so it is reachable only there — never over the
// TCP dashboard listener.
//
// The plan's preferred shape was a connect-go service generated by
// `buf generate` (proto/wb/daemon/v1/peers.proto). buf's remote plugins need
// network access this environment does not have, so this task takes the
// spec's explicit fallback instead: plain JSON handlers behind the same
// owner-token check. See the PR description for the tradeoff.
const peersRPCPrefix = peers.RPCPrefix

// newPeerAdminHTTPHandler serves the owner-token peer admin routes. mount is
// nil, or has a nil PeerAdmin, when no hub is configured — every route then
// answers 503 rather than panicking, so the RPC surface exists identically
// whether or not this daemon self-hosts.
type peerAdminClient struct{ httpClient *http.Client }

// newPeerAdminClient starts the local daemon if needed (an admin operation
// needs its owner token, minted at start) and returns a client authenticated
// against it.
func newPeerAdminClient(ctx context.Context, deps daemonDependencies, root string) (*peerAdminClient, error) {
	controller := newDaemonController(deps, root)
	result, err := controller.Start(ctx, daemonruntime.DefaultListen)
	if err != nil {
		return nil, fmt.Errorf("start local daemon: %w", err)
	}
	state, found, err := controller.LoadState()
	if err != nil {
		return nil, err
	}
	if !found || state.Status != daemon.StatusReady || !result.ProcessManagerRunning {
		return nil, errors.New("local daemon is not ready")
	}
	localClient := deps.LocalClient
	if localClient == nil {
		localClient = daemonruntime.LocalHTTPClient
	}
	httpClient, err := localClient(root, state.OwnerToken)
	if err != nil {
		return nil, err
	}
	return &peerAdminClient{httpClient: httpClient}, nil
}

// call posts request as JSON to path and decodes a 200 response into
// response (which may be nil to discard the body). A non-200 response
// becomes an *exitError carrying the daemon's {"error": "..."} message, at
// the findings exit code: the invocation was well-formed, but the operation
// itself was refused (an existing peer name, an unknown peer, and so on).
func (client *peerAdminClient) call(ctx context.Context, path string, request, response any) error {
	body, err := json.Marshal(request)
	if err != nil {
		return fmt.Errorf("encode request: %w", err)
	}
	httpRequest, err := http.NewRequestWithContext(ctx, http.MethodPost, daemonruntime.RPCBaseURL+path, bytes.NewReader(body))
	if err != nil {
		return err
	}
	httpRequest.Header.Set("Content-Type", "application/json")
	httpResponse, err := client.httpClient.Do(httpRequest)
	if err != nil {
		return fmt.Errorf("call local daemon: %w", err)
	}
	defer func() { _ = httpResponse.Body.Close() }()
	raw, err := io.ReadAll(io.LimitReader(httpResponse.Body, 1<<20))
	if err != nil {
		return fmt.Errorf("read daemon response: %w", err)
	}
	if httpResponse.StatusCode != http.StatusOK {
		var payload struct {
			Error string `json:"error"`
		}
		_ = json.Unmarshal(raw, &payload)
		message := strings.TrimSpace(payload.Error)
		if message == "" {
			message = strings.TrimSpace(string(raw))
		}
		if message == "" {
			message = httpResponse.Status
		}
		return &exitError{code: exitFindings, message: message}
	}
	if response == nil {
		return nil
	}
	if err := json.Unmarshal(raw, response); err != nil {
		return fmt.Errorf("decode daemon response: %w", err)
	}
	return nil
}

// daemonListenAddress resolves a running daemon's TCP listen address for the
// CLI's read path (`wb peers list`/`get`), without starting anything: a read
// command has no owner token to mint, so there is nothing useful to start
// for it. A daemon that is not running is reported plainly rather than
// silently opened.
func daemonListenAddress(deps daemonDependencies, root string) (string, error) {
	controller := newDaemonController(deps, root)
	state, found, err := controller.LoadState()
	if err != nil {
		return "", err
	}
	if !found || state.Status != daemon.StatusReady || strings.TrimSpace(state.Listen) == "" {
		return "", errors.New("the local daemon is not running; start it with `wb daemon start`")
	}
	return state.Listen, nil
}
