//go:build linux

package unix

import "golang.org/x/sys/unix"

const (
	O_PATH = unix.O_PATH

	SYS_LANDLOCK_CREATE_RULESET = unix.SYS_LANDLOCK_CREATE_RULESET
	SYS_LANDLOCK_ADD_RULE       = unix.SYS_LANDLOCK_ADD_RULE
	SYS_LANDLOCK_RESTRICT_SELF  = unix.SYS_LANDLOCK_RESTRICT_SELF

	LANDLOCK_CREATE_RULESET_VERSION = unix.LANDLOCK_CREATE_RULESET_VERSION
	LANDLOCK_RULE_PATH_BENEATH      = unix.LANDLOCK_RULE_PATH_BENEATH
	PR_SET_NO_NEW_PRIVS             = unix.PR_SET_NO_NEW_PRIVS

	LANDLOCK_ACCESS_FS_WRITE_FILE  = unix.LANDLOCK_ACCESS_FS_WRITE_FILE
	LANDLOCK_ACCESS_FS_REMOVE_DIR  = unix.LANDLOCK_ACCESS_FS_REMOVE_DIR
	LANDLOCK_ACCESS_FS_REMOVE_FILE = unix.LANDLOCK_ACCESS_FS_REMOVE_FILE
	LANDLOCK_ACCESS_FS_MAKE_CHAR   = unix.LANDLOCK_ACCESS_FS_MAKE_CHAR
	LANDLOCK_ACCESS_FS_MAKE_DIR    = unix.LANDLOCK_ACCESS_FS_MAKE_DIR
	LANDLOCK_ACCESS_FS_MAKE_REG    = unix.LANDLOCK_ACCESS_FS_MAKE_REG
	LANDLOCK_ACCESS_FS_MAKE_SOCK   = unix.LANDLOCK_ACCESS_FS_MAKE_SOCK
	LANDLOCK_ACCESS_FS_MAKE_FIFO   = unix.LANDLOCK_ACCESS_FS_MAKE_FIFO
	LANDLOCK_ACCESS_FS_MAKE_BLOCK  = unix.LANDLOCK_ACCESS_FS_MAKE_BLOCK
	LANDLOCK_ACCESS_FS_MAKE_SYM    = unix.LANDLOCK_ACCESS_FS_MAKE_SYM
	LANDLOCK_ACCESS_FS_REFER       = unix.LANDLOCK_ACCESS_FS_REFER
	LANDLOCK_ACCESS_FS_TRUNCATE    = unix.LANDLOCK_ACCESS_FS_TRUNCATE
)

var Syscall = unix.Syscall
var Syscall6 = unix.Syscall6
var Exec = unix.Exec
var Prctl = unix.Prctl
var Renameat2 = unix.Renameat2
var Gettid = unix.Gettid

const RENAME_NOREPLACE = unix.RENAME_NOREPLACE
