package quality

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestParallelGuardModuleRootReturnsErrorWhenCallerCannotBeResolved pins
// ParallelGuardModuleRoot's defensive branch for runtime.Caller failing --
// unreachable from a real, fixed skip=1 call, so it is exercised through
// the callerLookup seam instead.
//
//nolint:paralleltest // mutates the package-level callerLookup seam
func TestParallelGuardModuleRootReturnsErrorWhenCallerCannotBeResolved(t *testing.T) {
	original := callerLookup
	t.Cleanup(func() { callerLookup = original })
	callerLookup = func(int) (uintptr, string, int, bool) { return 0, "", 0, false }

	if _, err := ParallelGuardModuleRoot(); err == nil {
		t.Fatal("ParallelGuardModuleRoot returned no error when the caller could not be resolved")
	}
}

// TestParallelGuardModuleRootReturnsErrorWhenNoGoModExists pins the other
// walk-up failure: no go.mod anywhere above the caller's directory.
//
//nolint:paralleltest // mutates the package-level callerLookup seam
func TestParallelGuardModuleRootReturnsErrorWhenNoGoModExists(t *testing.T) {
	original := callerLookup
	t.Cleanup(func() { callerLookup = original })
	dir := t.TempDir()
	callerLookup = func(int) (uintptr, string, int, bool) {
		return 0, filepath.Join(dir, "caller.go"), 0, true
	}

	if _, err := ParallelGuardModuleRoot(); err == nil {
		t.Fatal("ParallelGuardModuleRoot returned no error when no go.mod exists above the caller")
	}
}

// TestParallelGuardModuleRootFindsRealModuleRoot pins the success path: this
// repository's own go.mod, found by walking up from this very file.
func TestParallelGuardModuleRootFindsRealModuleRoot(t *testing.T) {
	t.Parallel()
	root, err := ParallelGuardModuleRoot()
	if err != nil {
		t.Fatalf("ParallelGuardModuleRoot: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		t.Fatalf("resolved root %q has no go.mod: %v", root, err)
	}
}

func TestParseParallelBaselineReportsMissingFile(t *testing.T) {
	t.Parallel()
	if _, err := ParseParallelBaseline(filepath.Join(t.TempDir(), "missing.txt")); err == nil {
		t.Fatal("ParseParallelBaseline read a file that does not exist")
	}
}

func TestParseParallelBaselineRejectsEveryEntryMissingAReason(t *testing.T) {
	t.Parallel()
	path := filepath.Join(t.TempDir(), "baseline.txt")
	content := "pkg::TestGood\tgood reason\n" +
		"pkg::TestNoTab\n" +
		"pkg::TestEmptyReason\t\n" +
		"\n" +
		"# a comment line\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := ParseParallelBaseline(path)
	if err == nil {
		t.Fatal("ParseParallelBaseline accepted entries with no reason")
	}
	if !strings.Contains(err.Error(), "pkg::TestNoTab") || !strings.Contains(err.Error(), "pkg::TestEmptyReason") {
		t.Fatalf("error %q does not name every entry missing a reason", err)
	}
}

func TestParseParallelBaselineAcceptsWellFormedEntries(t *testing.T) {
	t.Parallel()
	path := filepath.Join(t.TempDir(), "baseline.txt")
	content := "# header comment\n\npkg::TestB\treason b\npkg::TestA\treason a\r\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	entries, err := ParseParallelBaseline(path)
	if err != nil {
		t.Fatalf("ParseParallelBaseline: %v", err)
	}
	if entries["pkg::TestA"] != "reason a" || entries["pkg::TestB"] != "reason b" {
		t.Fatalf("entries = %+v, want both keys with their reasons", entries)
	}
}

func TestFormatParallelBaselineSortsAndRendersEntries(t *testing.T) {
	t.Parallel()
	rendered := FormatParallelBaseline([]ParallelBaselineEntry{
		{Key: "pkg::TestZ", Reason: "z reason"},
		{Key: "pkg::TestA", Reason: "a reason"},
	})
	if !strings.HasPrefix(rendered, "# Generated by") {
		t.Fatalf("rendered baseline missing the generated-file header:\n%s", rendered)
	}
	aIndex := strings.Index(rendered, "pkg::TestA\ta reason")
	zIndex := strings.Index(rendered, "pkg::TestZ\tz reason")
	if aIndex < 0 || zIndex < 0 || aIndex > zIndex {
		t.Fatalf("rendered baseline is not sorted by key:\n%s", rendered)
	}
}

func TestPackageDirForFallsBackToPathWhenNotRelatable(t *testing.T) {
	t.Parallel()
	// A relative root against an absolute path cannot be made relative
	// without knowing the working directory; filepath.Rel refuses to guess.
	got := packageDirFor("relative/root", filepath.FromSlash("/absolute/root/pkg/foo_test.go"))
	want := filepath.ToSlash(filepath.Dir(filepath.FromSlash("/absolute/root/pkg/foo_test.go")))
	if got != want {
		t.Fatalf("packageDirFor fallback = %q, want %q", got, want)
	}
}

func TestPackageDirForResolvesRelativePackageDirectory(t *testing.T) {
	t.Parallel()
	root := filepath.FromSlash("/repo")
	path := filepath.FromSlash("/repo/internal/quality/foo_test.go")
	if got, want := packageDirFor(root, path), "internal/quality"; got != want {
		t.Fatalf("packageDirFor = %q, want %q", got, want)
	}
}

func TestChildNameReturnsTheKeyItselfWhenThereIsNoSlash(t *testing.T) {
	t.Parallel()
	if got := childName("TestNoSubtests"); got != "TestNoSubtests" {
		t.Fatalf("childName(%q) = %q, want the unchanged key", "TestNoSubtests", got)
	}
}

func TestChildNameReturnsTheSegmentAfterTheLastSlash(t *testing.T) {
	t.Parallel()
	if got := childName("pkg::TestOuter/inner/leaf"); got != "leaf" {
		t.Fatalf("childName = %q, want %q", got, "leaf")
	}
}

// funcTypeFromSource parses a single top-level function declaration and
// returns its *ast.FuncType, for exercising singleTestingTParam directly
// against synthetic signatures without writing any file to disk.
func funcTypeFromSource(t *testing.T, source string) *ast.FuncType {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "synthetic.go", "package p\n"+source, 0)
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	fd, ok := file.Decls[0].(*ast.FuncDecl)
	if !ok {
		t.Fatalf("fixture's first declaration is not a function: %#v", file.Decls[0])
	}
	return fd.Type
}

func TestSingleTestingTParamRejectsAnyShapeOtherThanExactlyOnePointerToTestingT(t *testing.T) {
	t.Parallel()
	cases := map[string]string{
		"no parameters":                       "func NoParams() {}\n",
		"two parameters":                      "func TwoParams(t *testing.T, u *testing.T) {}\n",
		"a value, not a pointer":              "func ValueParam(t testing.T) {}\n",
		"a pointer to another type":           "func WrongPointer(t *int) {}\n",
		"a pointer to another package's type": "func WrongPackage(t *other.T) {}\n",
	}
	for name, source := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			if singleTestingTParam(funcTypeFromSource(t, source)) {
				t.Fatalf("singleTestingTParam accepted a %s signature", name)
			}
		})
	}
}

func TestSingleTestingTParamAcceptsExactlyOnePointerToTestingT(t *testing.T) {
	t.Parallel()
	fn := funcTypeFromSource(t, "func TestOK(t *testing.T) {}\n")
	if !singleTestingTParam(fn) {
		t.Fatal("singleTestingTParam rejected a plain func(t *testing.T) signature")
	}
}

// commentedPositionFromSource parses source containing exactly one
// `// marker` line followed immediately by `func Marked() {}`, returning the
// parsed file, its FileSet, and the position of the `func` declaration --
// enough to exercise nolintParalleltestReason exactly the way scanFile does.
func commentedPositionFromSource(t *testing.T, source string) (*token.FileSet, *ast.File, token.Pos) {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "synthetic.go", source, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	fd, ok := file.Decls[len(file.Decls)-1].(*ast.FuncDecl)
	if !ok {
		t.Fatalf("fixture's last declaration is not a function: %#v", file.Decls[len(file.Decls)-1])
	}
	return fset, file, fd.Pos()
}

func TestNolintParalleltestReasonFindsNoComment(t *testing.T) {
	t.Parallel()
	fset, file, pos := commentedPositionFromSource(t, "package p\n\nfunc Marked() {}\n")
	reason, bare := nolintParalleltestReason(fset, file, pos)
	if reason != "" || bare {
		t.Fatalf("nolintParalleltestReason = (%q, %v), want (\"\", false) with no comment present", reason, bare)
	}
}

func TestNolintParalleltestReasonReportsBareDirectiveAsMissingAReason(t *testing.T) {
	t.Parallel()
	fset, file, pos := commentedPositionFromSource(t, "package p\n\n//nolint:paralleltest\nfunc Marked() {}\n")
	reason, bare := nolintParalleltestReason(fset, file, pos)
	if reason != "" || !bare {
		t.Fatalf("nolintParalleltestReason = (%q, %v), want (\"\", true) for a bare directive", reason, bare)
	}
}

func TestNolintParalleltestReasonReturnsTheStatedReason(t *testing.T) {
	t.Parallel()
	fset, file, pos := commentedPositionFromSource(t, "package p\n\n//nolint:paralleltest // a real reason\nfunc Marked() {}\n")
	reason, bare := nolintParalleltestReason(fset, file, pos)
	if bare || reason != "a real reason" {
		t.Fatalf("nolintParalleltestReason = (%q, %v), want (\"a real reason\", false)", reason, bare)
	}
}

// writeScanFixture writes one _test.go file under root/dir so ScanSerialTests
// (the real filepath.Walk-driven entry point) parses it, exercising the
// walk callback's own branches rather than scanFile in isolation.
func writeScanFixture(t *testing.T, root, dir, filename, content string) {
	t.Helper()
	full := filepath.Join(root, dir)
	if err := os.MkdirAll(full, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(full, filename), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestScanSerialTestsReportsAMissingRootAsAWalkFailure(t *testing.T) {
	t.Parallel()
	missing := filepath.Join(t.TempDir(), "does-not-exist")

	_, _, err := ScanSerialTests(missing)
	if err == nil {
		t.Fatal("ScanSerialTests accepted a root directory that does not exist")
	}
	if !strings.Contains(err.Error(), "walk") {
		t.Fatalf("error %q does not name the walk failure", err)
	}
}

func TestScanSerialTestsReportsAParseErrorAsAWalkFailure(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeScanFixture(t, root, "pkg", "broken_test.go", "package pkg\n\nfunc TestBroken(t *testing.T {\n")

	_, _, err := ScanSerialTests(root)
	if err == nil {
		t.Fatal("ScanSerialTests accepted a file with a syntax error")
	}
	if !strings.Contains(err.Error(), "walk") || !strings.Contains(err.Error(), "parse") {
		t.Fatalf("error %q does not name both the walk and the parse failure", err)
	}
}

func TestScanSerialTestsSkipsFunctionsWithTheWrongSignature(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeScanFixture(t, root, "pkg", "wrong_signature_test.go", `package pkg

import "testing"

func TestMain(m *testing.M) {}

func NotATestFunction() {}

func TestWrongParamCount(t *testing.T, extra int) {}

func TestRight(t *testing.T) {
	t.Parallel()
}
`)

	serial, bareNolint, err := ScanSerialTests(root)
	if err != nil {
		t.Fatalf("ScanSerialTests: %v", err)
	}
	if len(bareNolint) != 0 {
		t.Fatalf("bareNolint = %v, want none", bareNolint)
	}
	for _, entry := range serial {
		if entry.Key == "pkg::TestMain" || entry.Key == "pkg::TestWrongParamCount" || entry.Key == "pkg::TestRight" {
			t.Fatalf("ScanSerialTests reported %q, want it skipped or parallel", entry.Key)
		}
	}
}

func TestScanSerialTestsReportsABareNolintDirective(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeScanFixture(t, root, "pkg", "bare_nolint_test.go", `package pkg

import "testing"

//nolint:paralleltest
func TestBareDirective(t *testing.T) {
	t.Setenv("X", "1")
}
`)

	_, bareNolint, err := ScanSerialTests(root)
	if err != nil {
		t.Fatalf("ScanSerialTests: %v", err)
	}
	if len(bareNolint) != 1 || !strings.Contains(bareNolint[0], "pkg::TestBareDirective") {
		t.Fatalf("bareNolint = %v, want exactly one entry naming pkg::TestBareDirective", bareNolint)
	}
}

func TestScanSerialTestsExcludesATestExplainedByAReasonedNolintDirective(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeScanFixture(t, root, "pkg", "reasoned_nolint_test.go", `package pkg

import "testing"

//nolint:paralleltest // deliberately serial for this fixture
func TestReasonedDirective(t *testing.T) {
	t.Setenv("X", "1")
}
`)

	serial, bareNolint, err := ScanSerialTests(root)
	if err != nil {
		t.Fatalf("ScanSerialTests: %v", err)
	}
	if len(bareNolint) != 0 {
		t.Fatalf("bareNolint = %v, want none for a directive that carries a reason", bareNolint)
	}
	for _, entry := range serial {
		if entry.Key == "pkg::TestReasonedDirective" {
			t.Fatalf("ScanSerialTests reported %q as an offender despite its reasoned nolint directive", entry.Key)
		}
	}
}

func TestScanSerialTestsExcludesADirectoryUnderdParallelGuardExcludedDirs(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	excluded := ParallelGuardExcludedDirs[0]
	writeScanFixture(t, root, excluded, "excluded_test.go", `package excluded

import "testing"

func TestExcludedDirIsNeverScanned(t *testing.T) {}
`)

	serial, _, err := ScanSerialTests(root)
	if err != nil {
		t.Fatalf("ScanSerialTests: %v", err)
	}
	for _, entry := range serial {
		if strings.Contains(entry.Key, "TestExcludedDirIsNeverScanned") {
			t.Fatalf("ScanSerialTests scanned an excluded directory: %q", entry.Key)
		}
	}
}
