// Package quality's parallel-baseline logic backs two things that must never
// drift apart: TestParallelBaselineDoesNotRegress (the CI guard) and
// cmd/parallelbaseline (the tool a human runs to regenerate the committed
// baseline after a deliberate, reviewed decision to add a new serial test).
// Both call the exported functions in this file so there is exactly one
// implementation of "what counts as serial" and "what counts as a baseline
// key".
package quality

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

// ParallelGuardExcludedDirs are the subtrees sneat-dev/wb#623's test-speed
// sweep did not touch, because other agent lanes were actively editing their
// test files at the same time (cmd/wb is #623 step 3; hub and
// internal/runqueue belong to other in-flight lanes). Once those get their
// own pass this list should shrink, and eventually disappear.
var ParallelGuardExcludedDirs = []string{"cmd/wb", "hub", "internal/runqueue"}

// ParallelBaselineEntry is one committed line: a serial test or subtest,
// keyed by package directory + test name + subtest path (never by
// file:line, which shifts on every unrelated edit), with a mandatory reason.
type ParallelBaselineEntry struct {
	Key    string
	Reason string
}

// callerLookup abstracts runtime.Caller so ParallelGuardModuleRoot's
// defensive "the runtime could not resolve the caller" branch -- which
// cannot actually happen from a fixed skip=1 call in ordinary Go code -- is
// exercisable by a test, the same seam convention this repository already
// uses for Now func() time.Time.
var callerLookup = runtime.Caller

// ParallelGuardModuleRoot walks up from the calling file to the nearest
// go.mod.
func ParallelGuardModuleRoot() (string, error) {
	_, thisFile, _, ok := callerLookup(1)
	if !ok {
		return "", fmt.Errorf("resolve caller's own path")
	}
	dir := filepath.Dir(thisFile)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find module root above %s", thisFile)
		}
		dir = parent
	}
}

// ParseParallelBaseline reads the baseline file, keyed as
// "<key>\t<reason>" per line. Every entry must carry a non-empty reason;
// ParseParallelBaseline returns an error naming every entry that does not
// (callers surface all of them at once rather than failing on the first).
func ParseParallelBaseline(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read baseline %s: %w", path, err)
	}
	out := map[string]string{}
	var emptyReason []string
	for i, line := range strings.Split(string(data), "\n") {
		line = strings.TrimRight(line, "\r")
		if strings.TrimSpace(line) == "" || strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		parts := strings.SplitN(line, "\t", 2)
		key := strings.TrimSpace(parts[0])
		reason := ""
		if len(parts) == 2 {
			reason = strings.TrimSpace(parts[1])
		}
		if reason == "" {
			emptyReason = append(emptyReason, fmt.Sprintf("%s:%d: %q has no reason", path, i+1, key))
			continue
		}
		out[key] = reason
	}
	if len(emptyReason) > 0 {
		return nil, fmt.Errorf("%d baseline entr(y/ies) missing a reason:\n%s", len(emptyReason), strings.Join(emptyReason, "\n"))
	}
	return out, nil
}

// FormatParallelBaseline renders entries as the committed file format:
// sorted by key, tab-separated key and reason, one per line.
func FormatParallelBaseline(entries []ParallelBaselineEntry) string {
	sorted := append([]ParallelBaselineEntry(nil), entries...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Key < sorted[j].Key })
	var b strings.Builder
	b.WriteString("# Generated by `go run ./internal/quality/cmd/parallelbaseline`. Do not\n")
	b.WriteString("# hand-edit: regenerate after a reviewed decision to add a new serial test,\n")
	b.WriteString("# and check in the result. Format: <package dir>::<TestName>[/<subtest\n")
	b.WriteString("# path>]\\t<reason>. Every entry needs a real reason; the guard\n")
	b.WriteString("# (TestParallelBaselineDoesNotRegress) rejects an empty one.\n")
	for _, e := range sorted {
		fmt.Fprintf(&b, "%s\t%s\n", e.Key, e.Reason)
	}
	return b.String()
}

// testNode is one Test function or t.Run subtest, at any nesting depth.
type testNode struct {
	key           string // package/dir::TestName[/subtest/path...]
	pos           token.Pos
	isParallel    bool
	selfReason    string // non-empty if this node's own body (not a nested subtest) taints it
	children      []*testNode
	nolintReason  string // reason text found on a //nolint:paralleltest // <reason> comment
	hasBareNolint bool   // a //nolint:paralleltest with no reason text
}

// ScanSerialTests walks every _test.go file under root (skipping
// ParallelGuardExcludedDirs) and returns one entry per serial Test function
// or t.Run subtest, at any nesting depth, with an automatically classified
// reason. It also returns the set of nolint-without-a-reason sites, which
// the guard treats as offenders in their own right (S2/B2: a bare
// `//nolint:paralleltest` is no longer accepted).
func ScanSerialTests(root string) (serial []ParallelBaselineEntry, bareNolint []string, err error) {
	fset := token.NewFileSet()
	walkErr := filepath.Walk(root, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if info.IsDir() {
			base := info.Name()
			if base == ".git" || base == "node_modules" || base == "vendor" || (strings.HasPrefix(base, ".") && base != ".") {
				return filepath.SkipDir
			}
			rel, relErr := filepath.Rel(root, path)
			if relErr == nil {
				relSlash := filepath.ToSlash(rel)
				for _, excluded := range ParallelGuardExcludedDirs {
					if relSlash == excluded || strings.HasPrefix(relSlash, excluded+"/") {
						return filepath.SkipDir
					}
				}
			}
			return nil
		}
		if !strings.HasSuffix(path, "_test.go") {
			return nil
		}
		pkgDir := packageDirFor(root, path)
		file, parseErr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if parseErr != nil {
			return fmt.Errorf("parse %s: %w", path, parseErr)
		}
		fileSerial, fileBareNolint := scanFile(fset, file, pkgDir)
		serial = append(serial, fileSerial...)
		bareNolint = append(bareNolint, fileBareNolint...)
		return nil
	})
	if walkErr != nil {
		return nil, nil, fmt.Errorf("walk %s: %w", root, walkErr)
	}
	return serial, bareNolint, nil
}

// packageDirFor renders path as a slash-separated directory relative to
// root, falling back to path itself when it cannot be made relative (mixed
// absolute/relative inputs, which never occurs through ScanSerialTests's own
// filepath.Walk but is exercised directly by a unit test).
func packageDirFor(root, path string) string {
	rel, relErr := filepath.Rel(root, path)
	if relErr != nil {
		rel = path
	}
	return filepath.ToSlash(filepath.Dir(rel))
}

func scanFile(fset *token.FileSet, file *ast.File, pkgDir string) ([]ParallelBaselineEntry, []string) {
	var serial []ParallelBaselineEntry
	var bareNolint []string
	for _, decl := range file.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Body == nil || fd.Recv != nil {
			continue
		}
		if fd.Name.Name == "TestMain" || !strings.HasPrefix(fd.Name.Name, "Test") {
			continue
		}
		if !singleTestingTParam(fd.Type) {
			continue
		}
		root := buildTestNode(fd.Body, fmt.Sprintf("%s::%s", pkgDir, fd.Name.Name), fd.Pos())
		var walk func(n *testNode)
		walk = func(n *testNode) {
			n.nolintReason, n.hasBareNolint = nolintParalleltestReason(fset, file, n.pos)
			if n.hasBareNolint {
				bareNolint = append(bareNolint, fmt.Sprintf("%s:%d: %s has a //nolint:paralleltest with no reason", file.Name.Name, fset.Position(n.pos).Line, n.key))
			}
			for _, c := range n.children {
				walk(c)
			}
		}
		walk(root)
		collectOffenders(root, &serial)
	}
	return serial, bareNolint
}

func collectOffenders(n *testNode, out *[]ParallelBaselineEntry) {
	for _, c := range n.children {
		collectOffenders(c, out)
	}
	if n.isParallel {
		return
	}
	if n.nolintReason != "" {
		return
	}
	*out = append(*out, ParallelBaselineEntry{Key: n.key, Reason: classifyReason(n)})
}

func classifyReason(n *testNode) string {
	if n.selfReason != "" {
		return n.selfReason
	}
	for _, c := range n.children {
		if !c.isParallel && c.nolintReason == "" {
			return fmt.Sprintf("kept serial because a nested subtest must stay serial: %s", childName(c.key))
		}
	}
	return "serial pending case-by-case review (sneat-dev/wb#623 baseline)"
}

func childName(key string) string {
	idx := strings.LastIndex(key, "/")
	if idx < 0 {
		return key
	}
	return key[idx+1:]
}

// buildTestNode recurses into node's own statements, stopping at (but
// recording) each nested t.Run subtest -- this is the M2 fix: every
// subtest, at every depth, gets its own node and its own baseline key.
func buildTestNode(body *ast.BlockStmt, key string, pos token.Pos) *testNode {
	n := &testNode{key: key, pos: pos}
	ordinal := 0
	ast.Inspect(body, func(node ast.Node) bool {
		if node == body {
			return true
		}
		if lit, ok := node.(*ast.FuncLit); ok {
			_ = lit
			return false // a bare closure that is not a t.Run argument: don't descend
		}
		if call, ok := node.(*ast.CallExpr); ok {
			if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Parallel" && len(call.Args) == 0 {
				n.isParallel = true
			}
			if reason := selfTaintReason(call); reason != "" && n.selfReason == "" {
				n.selfReason = reason
			}
			if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Run" && len(call.Args) == 2 {
				if subLit, ok := call.Args[1].(*ast.FuncLit); ok && singleTestingTParam(subLit.Type) {
					ordinal++
					name := subtestName(call.Args[0], ordinal)
					child := buildTestNode(subLit.Body, key+"/"+name, subLit.Pos())
					n.children = append(n.children, child)
					return false
				}
			}
		}
		return true
	})
	return n
}

// subtestName prefers the literal string passed to t.Run (matching how
// `go test -run` addresses subtests); a name built at runtime (from a loop
// variable, fmt.Sprintf, etc.) has no static identity, so it falls back to
// its 1-based position among its siblings.
func subtestName(arg ast.Expr, ordinal int) string {
	if lit, ok := arg.(*ast.BasicLit); ok && lit.Kind == token.STRING {
		if unquoted, err := strconv.Unquote(lit.Value); err == nil && unquoted != "" {
			return unquoted
		}
	}
	return fmt.Sprintf("#%d", ordinal)
}

func singleTestingTParam(ft *ast.FuncType) bool {
	if ft.Params == nil || len(ft.Params.List) != 1 {
		return false
	}
	field := ft.Params.List[0]
	star, ok := field.Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	sel, ok := star.X.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	pkgIdent, ok := sel.X.(*ast.Ident)
	return ok && pkgIdent.Name == "testing" && sel.Sel.Name == "T"
}

// selfTaintReason recognizes the handful of calls that make Go's own testing
// package panic under t.Parallel (t.Setenv, t.Chdir) or that are known,
// named seams reaching the same restriction indirectly (testenv.Isolate).
// It is deliberately narrow and precise rather than exhaustive: a node this
// misses still gets an offender entry, just with the generic fallback
// reason, and still needs a baseline row like everything else -- it is
// never silently allowed through.
func selfTaintReason(call *ast.CallExpr) string {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return ""
	}
	switch sel.Sel.Name {
	case "Setenv", "Chdir":
		if id, ok := sel.X.(*ast.Ident); ok && id.Name == "t" {
			return "calls t." + sel.Sel.Name + ", which Go's testing package forbids combined with t.Parallel (on this test or any ancestor)"
		}
	case "Isolate":
		if id, ok := sel.X.(*ast.Ident); ok && id.Name == "testenv" {
			return "calls testenv.Isolate, which calls t.Setenv internally and so forbids t.Parallel the same way"
		}
	}
	return ""
}

func nolintParalleltestReason(fset *token.FileSet, file *ast.File, pos token.Pos) (reason string, bare bool) {
	posLine := fset.Position(pos).Line
	for _, cg := range file.Comments {
		for _, c := range cg.List {
			cLine := fset.Position(c.Pos()).Line
			if cLine != posLine-1 && cLine != posLine {
				continue
			}
			text := c.Text
			idx := strings.Index(text, "nolint:paralleltest")
			if idx < 0 {
				continue
			}
			rest := text[idx+len("nolint:paralleltest"):]
			rest = strings.TrimSpace(rest)
			rest = strings.TrimPrefix(rest, "//")
			rest = strings.TrimSpace(rest)
			if rest == "" {
				return "", true
			}
			return rest, false
		}
	}
	return "", false
}
